package io.github.andriyo.shadowdroid.studio

internal object BridgeConfig {
    const val ROOT_CONTEXT = "/"
    const val PORT_PROPERTY = "shadowdroid.debugger.port"
    const val PORT_ENV = "SHADOWDROID_STUDIO_DEBUGGER_PORT"
    const val REGISTRY_DIR = ".shadowdroid"
    const val REGISTRY_FILE = "studio-debugger.json"
}

internal object BridgeRoutes {
    const val STATUS = "/v1/status"
    const val SESSIONS = "/v1/sessions"
    const val SESSION_CONTROL = "/v1/session/control"
    const val SESSION_STACK = "/v1/session/stack"
    const val SESSION_THREADS = "/v1/session/threads"
    const val SESSION_VARIABLES = "/v1/session/variables"
    const val SESSION_EVALUATE = "/v1/session/evaluate"
    const val SESSION_INSPECT = "/v1/session/inspect"
    const val SESSION_COROUTINES = "/v1/session/coroutines"
    const val SESSION_COROUTINES_THREADS = "/v1/session/coroutines/threads"
    const val SESSION_COROUTINES_CONTINUATION = "/v1/session/coroutines/continuation"
    const val SESSION_COROUTINES_FLOW = "/v1/session/coroutines/flow"
    const val WATCHES = "/v1/watches"
    const val WATCHES_ADD = "/v1/watches/add"
    const val WATCHES_REMOVE = "/v1/watches/remove"
    const val WATCHES_CLEAR = "/v1/watches/clear"
    const val CLIENTS = "/v1/clients"
    const val BREAKPOINTS = "/v1/breakpoints"
    const val BREAKPOINT_LINE = "/v1/breakpoints/line"
    const val BREAKPOINT_EXCEPTION = "/v1/breakpoints/exception"
    const val BREAKPOINT_METHOD = "/v1/breakpoints/method"
    const val BREAKPOINT_FIELD = "/v1/breakpoints/field"
    const val BREAKPOINT_UPDATE = "/v1/breakpoints/update"
    const val BREAKPOINT_REMOVE = "/v1/breakpoints/remove"
    const val ATTACH = "/v1/attach"
    const val LAYOUT_SNAPSHOT = "/v1/layout/snapshot"
    const val LAYOUT_RECOMPOSITIONS = "/v1/layout/recompositions"
    const val LAYOUT_SOURCE = "/v1/layout/source"
}

internal object BridgeQuery {
    const val ACCESS = "access"
    const val ACTION = "action"
    const val CAUGHT = "caught"
    const val CLASS = "class"
    const val CLEAR_CONDITION = "clear_condition"
    const val CLEAR_LOG_EXPRESSION = "clear_log_expression"
    const val CONDITION = "condition"
    const val CONFIGURATION = "configuration"
    const val DEBUGGER = "debugger"
    const val DEPTH = "depth"
    const val DEVICE = "device"
    const val DIALOG = "dialog"
    const val DRAW_ID = "draw_id"
    const val ENABLED = "enabled"
    const val ENTRY = "entry"
    const val EXCEPTION = "exception"
    const val EXIT = "exit"
    const val EXPRESSION = "expression"
    const val FIELD = "field"
    const val FILE = "file"
    const val FRAME = "frame"
    const val HANDLE = "handle"
    const val ID = "id"
    const val LINE = "line"
    const val LIMIT = "limit"
    const val LOG_EXPRESSION = "log_expression"
    const val LOG_MESSAGE = "log_message"
    const val LOG_STACK = "log_stack"
    const val MAX_ARRAY_ITEMS = "max_array_items"
    const val MAX_FIELDS = "max_fields"
    const val METHOD = "method"
    const val MODE = "mode"
    const val MODIFICATION = "modification"
    const val NAME = "name"
    const val PACKAGE = "package"
    const val PASS_COUNT = "pass_count"
    const val PATH = "path"
    const val PID = "pid"
    const val PROJECT = "project"
    const val RESET = "reset"
    const val RID = "rid"
    const val SESSION = "session"
    const val SUSPEND = "suspend"
    const val TEMPORARY = "temporary"
    const val TEXT = "text"
    const val THREAD = "thread"
    const val TIMEOUT_MS = "timeout_ms"
    const val UNCAUGHT = "uncaught"
}

internal object BridgeValues {
    const val ACTION_ATTACH = "attach"
    const val ACTION_PAUSE = "pause"
    const val ACTION_RESUME = "resume"
    const val ACTION_STEP_INTO = "step_into"
    const val ACTION_STEP_OUT = "step_out"
    const val ACTION_STEP_OVER = "step_over"
    const val ACTION_STOP = "stop"
    const val ANDROID_CONNECT_DEBUGGER_ACTION = "AndroidConnectDebuggerAction"
    const val EVAL_MODE_JDI_PATH = "jdi_path"
    const val EVAL_MODE_OBJECT_HANDLE = "object_handle"
    const val LAYOUT_INSPECTOR_SOURCE = "android_studio_layout_inspector"
    const val LAYOUT_RECOMPOSITIONS = "layout_recompositions"
    const val LAYOUT_SNAPSHOT = "layout_snapshot"
    const val LAYOUT_SOURCE = "layout_source"
}
